# Generated by Django 4.1.7 on 2023-03-16 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0005_reviews_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='average_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='reviews',
            name='review_count',
            field=models.IntegerField(default=0),
        ),
    ]
