# Generated by Django 4.1.7 on 2023-03-17 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0006_reviews_average_rating_reviews_review_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='average_rating',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='review_count',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='average_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='review_count',
            field=models.IntegerField(default=0),
        ),
    ]
